### ISSUE TITLE
Error when trying to use Sharpener with BOI on 1.9, caused by outdated installation instructions in README of Sharpener mod

### ISSUE THREAD

**Issue by TYTheBeast** [PJB3005/RainWorldMods#2]
When attempting to use Sharpener, I get the following error:
![image](https://user-images.githubusercontent.com/19373069/222544645-e482aabf-bd3f-4ff8-9c26-ae1b6f9046fe.png)
Sharpener is the only mod installed, so I'm not sure _why_ there's a conflict of keys.
After displaying this error, the game starts but the screen is completely black.

**Comment by TYTheBeast** [comment]
Nevermind. The reddit post that brought me here was quite old, and since then Rain World has updated a lot.
Because of that, the installation instructions I followed were also outdated. Apologies for the misunderstanding :p

It would be best to update the README file of the Sharpener mod

**Comment by vanillafox0620** [comment]
How did you fix this? I'm getting the exact same error, and nothing is helping.

**Comment by PJB3005** [comment]
You don't use BOI on Rain World 1.9, Remix has a built-in mod loader.

Also, use the version from the Steam Workshop, not the one from RainDB.

**Comment by lane-ftw** [comment]
> You don't use BOI on Rain World 1.9, Remix has a built-in mod loader.
> 
> Also, use the version from the Steam Workshop, not the one from RainDB.

So this is steam only now then?
EDIT: https://github.com/PJB3005/RainWorldMods/releases/tag/sharpener-2.0.0
For anyone else that needs this link.

**Comment by TYTheBeast** [comment]
> You don't use BOI on Rain World 1.9, Remix has a built-in mod loader.
> 
> Also, use the version from the Steam Workshop, not the one from RainDB.

Not everyone can use the Steam version

**Comment by PJB3005** [comment]
Yes, https://github.com/PJB3005/RainWorldMods/releases/tag/sharpener-2.0.0 is the version for non-Steam.
