### ISSUE TITLE
How to set to "sharper" mode?

### ISSUE THREAD

**Issue by 16BitRun** [PJB3005/RainWorldMods#4]
You say your mod has three modes:

"game default" which is the original game.
"sharper" which is the recommended mode. Purely a better upscaler.
"native resolution" which renders the game directly at max resolution, but can cause various artifacts and distortions.

How do you change the mode to sharper in the game? I still in using BOI like you instructed where or how do I set it to the sharper mode and how do I know that is working? Thank you so much.

**Comment by PJB3005** [comment]
Are you talking about the version on the Steam workshop, or the one for RW 1.5? Because they're completely different.

The Steam Workshop version is working if the mod loaded correctly (ie it has a Remix settings menu if you click on the mod name).

**Comment by 16BitRun** [comment]
> Are you talking about the version on the Steam workshop, or the one for RW 1.5? Because they're completely different.
> 
> The Steam Workshop version is working if the mod loaded correctly (ie it has a Remix settings menu if you click on the mod name).

Oh, Ok. I just installed the Steam Workshop version and with your help, I found the Remix settings. Thank you. 🙏
